export const POLICY_PRESETS = {
  "dev-default": {
    label: "dev-default（DML 自由、DDL 需审批、危险操作禁止）",
    description: "适合开发环境，SELECT/INSERT/UPDATE/DELETE 自由，DDL 需审批",
    allowedStatementTypes: [
      "select",
      "insert",
      "update",
      "delete",
      "create_table",
      "create_index",
      "drop_table",
      "alter_table",
      "drop_index",
      "show_tables",
      "show_columns",
      "show_create_table",
    ],
    needApprovalStatementTypes: [
      "create_table",
      "drop_table",
      "alter_table",
      "create_index",
      "drop_index",
    ],
    blockedStatementTypes: [
      "drop_database",
      "drop_schema",
      "truncate",
      "grant",
      "revoke",
      "call",
      "create_database",
      "alter_database",
    ],
    enforceLimit: true,
    maxLimit: 1000,
  },
  "readonly-strict": {
    label: "readonly-strict（全只读、强制 LIMIT 500）",
    description: "适合只读场景，只允许 SELECT 和 SHOW",
    allowedStatementTypes: [
      "select",
      "show_tables",
      "show_columns",
      "show_create_table",
    ],
    needApprovalStatementTypes: [],
    blockedStatementTypes: [
      "drop_database",
      "drop_schema",
      "truncate",
      "grant",
      "revoke",
      "call",
      "create_database",
      "alter_database",
    ],
    enforceLimit: true,
    maxLimit: 500,
  },
  "demo-loose": {
    label: "demo-loose（全允许、仅极端危险需审批）",
    description: "适合演示，几乎全部允许，仅 DROP DATABASE 等需审批",
    allowedStatementTypes: ["<all>"],
    needApprovalStatementTypes: ["drop_database", "drop_schema", "truncate"],
    blockedStatementTypes: [],
    enforceLimit: true,
    maxLimit: 100,
  },
} as const;

export type PolicyPresetName = keyof typeof POLICY_PRESETS;
